export enum TirePosition {
  FRONT_LEFT = 'FRONT_LEFT',
  FRONT_RIGHT = 'FRONT_RIGHT',
  REAR_LEFT = 'REAR_LEFT',
  REAR_RIGHT = 'REAR_RIGHT',
  SPARE = 'SPARE',
  TIRE_1 = 'TIRE_1',
  TIRE_2 = 'TIRE_2',
  TIRE_3 = 'TIRE_3',
  TIRE_4 = 'TIRE_4',
  TIRE_5 = 'TIRE_5',
  TIRE_6 = 'TIRE_6',
  TIRE_7 = 'TIRE_7',
  TIRE_8 = 'TIRE_8',
  TIRE_9 = 'TIRE_9',
  TIRE_10 = 'TIRE_10',
  TIRE_11 = 'TIRE_11',
  TIRE_12 = 'TIRE_12',
}
